"""add administrative documents

Revision ID: 56e917b4c566
Revises: 6970f4e12ed7
Create Date: 2026-05-05 14:51:05.564387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e917b4c566'
down_revision: Union[str, Sequence[str], None] = '6970f4e12ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('source_ubication_id', sa.Integer(), nullable=True),
    sa.Column('target_ubication_id', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_ubication_id'], ['ubications.id'], ),
    sa.ForeignKeyConstraint(['target_ubication_id'], ['ubications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrative_document_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['administrative_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('loan_request_items_device_id_fkey'), 'loan_request_items', type_='foreignkey')
    op.create_foreign_key(None, 'loan_request_items', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan_request_items', type_='foreignkey')
    op.create_foreign_key(op.f('loan_request_items_device_id_fkey'), 'loan_request_items', 'devices', ['device_id'], ['id'])
    op.drop_table('administrative_document_items')
    op.drop_table('administrative_documents')
    # ### end Alembic commands ###
