"""add additional items to loan requests

Revision ID: 6381b73bca4a
Revises: d722b07a1623
Create Date: 2026-06-11 19:25:43.487004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6381b73bca4a'
down_revision: Union[str, Sequence[str], None] = 'd722b07a1623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('loan_request_items_device_id_fkey'), 'loan_request_items', type_='foreignkey')
    op.create_foreign_key(None, 'loan_request_items', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.add_column('loan_requests', sa.Column('additional_items', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_requests', 'additional_items')
    op.drop_constraint(None, 'loan_request_items', type_='foreignkey')
    op.create_foreign_key(op.f('loan_request_items_device_id_fkey'), 'loan_request_items', 'devices', ['device_id'], ['id'])
    # ### end Alembic commands ###
