/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/layout/AppTopbar.vue')['default']
    AuthLayout: typeof import('./src/components/layout/AuthLayout.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    BaseHeader: typeof import('./src/components/base/BaseHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CatalogTable: typeof import('./src/components/CatalogTable.vue')['default']
    CategoryForm: typeof import('./src/components/CategoryForm.vue')['default']
    CategorySection: typeof import('./src/components/CategorySection.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    copy: typeof import('./src/components/dialogs/UserDetailsDialog copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DevicesStatusBadge: typeof import('./src/components/ui/DevicesStatusBadge.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Label: typeof import('primevue/label')['default']
    LoanStatusBadge: typeof import('./src/components/ui/LoanStatusBadge.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    TodoStatsCards: typeof import('./src/components/TodoStatsCards.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    UserDeleteConfirmDialog: typeof import('./src/components/dialogs/UserDeleteConfirmDialog.vue')['default']
    UserDetail: typeof import('./src/components/dialogs/UserDetail.vue')['default']
    UserDetailsDialog: typeof import('./src/components/dialogs/UserDetailsDialog.vue')['default']
    UserForm: typeof import('./src/components/forms/UserForm.vue')['default']
    UserUpdateDialog: typeof import('./src/components/forms/UserUpdateDialog.vue')['default']
    UserUpdateForm: typeof import('./src/components/forms/UserUpdateForm.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
